name: tests-api-gateway

on:
  pull_request:
     paths:
       - 'api-gateway/**'

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: cd Auth-service && npm install && npm run prestart
