name: tests-instructor-service

on:
  pull_request:
     paths:
       - 'instructor/**'

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: cd Auth-service && npm install && npm run prestart
